# # 2D Two-Phase Flow on the SPE11a Geometry
# <tags: CO2, Compositional, Introduction>
# A simple two-phase miscible CO2-brine flow example that reuses the geometry,
# permeability and porosity of the SPE11a benchmark (a 2.8 m × 1.2 m vertical
# cross-section with 7 facies). The domain is initially fully saturated with a
# heavy liquid phase. A lighter vapor phase is injected from two point source
# terms — placed at the SPE11a injection cells — and rises towards the top
# under gravity.
#
# Three of the four boundaries are closed (no-flow, the JutulDarcy default).
# The top boundary is an open Dirichlet pressure boundary that lets the
# displaced fluids escape.
#
# The SPE11a deck (generated by pyopmspe11) contains a sealing facies with zero
# permeability. As in the SPE10 example, we remove these cells from the mesh
# rather than simulating through them — leaving them in would create isolated,
# non-flowing regions that hurt convergence.
#
# Generate the deck before running this script:
#   cd examples/workflow/spe11a_data && uv run pyopmspe11 -i input.toml -m deck -o output

using Jutul, JutulDarcy, GeoEnergyIO
using HYPRE
using GLMakie
using SpecialFunctions: erf

Darcy, bar, kg, meter, day = si_units(:darcy, :bar, :kilogram, :meter, :day)
mD = 1e-3 * Darcy
hour = 3600.0   # seconds

deck_dir = joinpath(@__DIR__, "spe11a_data", "output", "deck")
deck_path = joinpath(deck_dir, "OUTPUT.DATA")

# ## Parse the facies map from FLUXNUM.INC
# GeoEnergyIO does not support FLUXNUM or EQUALREG, so we parse the run-length
# encoded integer file directly to get one facies index per cell.
function parse_eclipse_rle_int(filepath)
    values = Int[]
    open(filepath) do f
        for line in eachline(f)
            line = split(strip(line), "--")[1]
            for token in split(line)
                token == "/" && return values
                if contains(token, "*")
                    n, v = split(token, "*")
                    append!(values, fill(parse(Int, v), parse(Int, n)))
                elseif all(c -> isdigit(c) || c == '-', token)
                    push!(values, parse(Int, token))
                end
            end
        end
    end
    return values
end

facies = parse_eclipse_rle_int(joinpath(deck_dir, "FLUXNUM.INC"))

# Permeability [mD] and porosity per facies (facies 7 is the sealing rock).
perm_mD = [44529.9988, 506624.985, 1013249.97, 2026499.95, 4052999.88, 10132499.7, 0.0]
phi_tab = [0.44, 0.43, 0.44, 0.45, 0.43, 0.46, 1e-6]

# ## Parse the SPE11a saturation-function tables
# The generated deck writes the benchmark constitutive laws in SGWFN as
# [Sg, krg, krw, pc] with pc in METRIC deck pressure units (bar).
function parse_sgwfn_tables(filepath)
    tables = Matrix{Float64}[]
    rows = Vector{Float64}[]
    in_sgwfn = false
    open(filepath) do f
        for line in eachline(f)
            line = strip(split(line, "--")[1])
            isempty(line) && continue
            for token in split(line)
                if token == "SGWFN"
                    in_sgwfn = true
                    continue
                end
                in_sgwfn || continue
                if token == "/"
                    if !isempty(rows)
                        push!(tables, reduce(vcat, transpose.(rows)))
                        empty!(rows)
                    end
                    continue
                end
                push!(rows, [parse(Float64, token)])
                if length(rows) >= 4 && all(length(r) == 1 for r in rows[end-3:end])
                    vals = vcat(rows[end-3:end]...)
                    resize!(rows, length(rows) - 4)
                    push!(rows, vals)
                end
            end
        end
    end
    return tables
end

sgwfn_tables = parse_sgwfn_tables(joinpath(deck_dir, "TABLES.INC"))

# ## Register OPM-specific keywords for the parser to skip
# We only need the grid geometry from the deck, so we skip the keywords that
# GeoEnergyIO does not understand and inject our own per-cell properties below.
let skip = GeoEnergyIO.InputParser.skip_kw!
    skip(:DISGASW, 0)
    skip(:VAPWAT, 0)
    skip(:EQUALREG, Inf)
    skip(:BCCON, Inf)
    skip(:SGWFN, Inf)
    skip(:DIFFAWAT, 1)
    skip(:DIFFAGAS, 1)
    skip(:THCO2MIX, 1)
    skip(:BCPROP, Inf)
end

# ## Parse the deck and inject facies-based properties
data = parse_data_file(deck_path)
n_cells = length(facies)
poro_full = [phi_tab[facies[c]] for c in 1:n_cells]
permx_full = [perm_mD[facies[c]] * mD for c in 1:n_cells]

data["GRID"]["PORO"] = poro_full
data["GRID"]["PERMX"] = permx_full
data["GRID"]["PERMY"] = permx_full
data["GRID"]["PERMZ"] = permx_full   # isotropic

# Build the full domain just to recover the SPE11a mesh geometry.
full_domain = reservoir_domain(data)
full_mesh = physical_representation(full_domain)

# ## Remove the sealing (zero-permeability) cells
# Following the SPE10 example, we drop the cells of the impermeable facies and
# extract a submesh containing only the active cells.
active = findall(facies .!= 7)
mesh = extract_submesh(full_mesh, active)

poro = poro_full[active]
perm = permx_full[active]
# Molecular diffusion per phase (SPE11a `diffusion` in input.toml): liquid 1e-9,
# gas 1.6e-5 [m^2/s]. The co2brine phases are ordered (LiquidPhase, VaporPhase),
# so row 1 = liquid, row 2 = gas. It must be given as an (nphase x ncell) matrix
# (one value per cell, per phase). Internally this becomes per-phase face
# diffusivities (D_alpha * porosity), adding Fickian component fluxes from
# gradients of the dissolved-CO2 / vaporized-H2O mass fractions.
diffusion = repeat([1e-9, 1.6e-5], 1, length(active))
domain = reservoir_domain(mesh, permeability=perm, porosity=poro, diffusion=diffusion)

# ## Locate the SPE11a injection cells
# SPE11a defines two injection locations. The pyopmspe11 deck places them at
# full-grid cells (i,j,k) = (91,1,101) (lower) and
# (180,1,43) (upper). We map these onto the active submesh (the seal cells were
# removed) by matching the logical (i,j,k) index, which `extract_submesh`
# preserves.
inj_ijk = [(91, 1, 101), (180, 1, 43)]
nc_full = number_of_cells(full_mesh)
inj_full = [findfirst(c -> cell_ijk(full_mesh, c) == ijk, 1:nc_full) for ijk in inj_ijk]
inj_cells = [searchsortedfirst(active, c) for c in inj_full]
well_radius = 9e-4   # SPE11a well bore radius [m] (input.toml `radius`)
injectors = [
    setup_well(domain, inj_cells[1], name=:Injector1, simple_well=true, radius=well_radius),
    setup_well(domain, inj_cells[2], name=:Injector2, simple_well=true, radius=well_radius),
]

# ## Miscible CO2-brine model with SPE11a constitutive laws
# The :co2brine model uses the CSP11/SPE11 H2O-CO2 property tables and K-values,
# so dissolved CO2 in brine and vaporized water in CO2 are represented.
domain[:temperature] = fill(20.0 + 273.15, number_of_cells(domain))
model = setup_reservoir_model(domain, :co2brine,
    wells=injectors,
    co2_physics=:kvalue,
    dz_max=0.05,
    dp_max_rel=0.1,
    fast_flash=true)

active_facies = facies[active]
# SPE11a capillary-pressure parameters per facies (input.toml `safu`): irreducible
# water saturation `swi` and entry pressure `pen` [Pa]. The generated deck clamps
# the erf capillary curve at penmax = 2500 Pa, but the benchmark description
# prescribes a maximum capillary pressure of 95000 Pa, so we recompute Pcgw
# analytically here rather than using the clamped deck values.
pc_swi = [0.32, 0.14, 0.12, 0.12, 0.12, 0.10, 0.0]
pc_pen = [1500.0, 300.0, 100.0, 25.0, 10.0, 1.0, 0.0]
penmax = 95000.0   # SPE11a maximum capillary pressure [Pa]
krw_tables = []
krg_tables = []
pcgw_tables = []
for (i, tab) in enumerate(sgwfn_tables)
    sg = tab[:, 1]
    krg = tab[:, 2]
    krw = tab[:, 3]
    swi, pen = pc_swi[i], pc_pen[i]
    pcgw = map(sg) do sg_i
        t = (1.0 - sg_i - swi) / (1.0 - swi)   # normalized effective water saturation
        t > 1e-10 ? penmax * erf(pen * t^(-0.5) * sqrt(π) / (2.0 * penmax)) : penmax
    end

    sw = reverse(1.0 .- sg)
    push!(krw_tables, PhaseRelativePermeability(sw, reverse(krw), label=:w))
    push!(krg_tables, PhaseRelativePermeability(sg, krg, label=:g))
    push!(pcgw_tables, get_1d_interpolator(sg, pcgw, constant_dx=false))
end

replace_variables!(model,
    RelativePermeabilities=RelativePermeabilities(
        (tuple(krw_tables...), tuple(krg_tables...)),
        regions=active_facies
    )
)
set_secondary_variables!(
    reservoir_model(model),
    CapillaryPressure=JutulDarcy.SimpleCapillaryPressure(
        (tuple(pcgw_tables...),),
        regions=active_facies
    )
)

# ## Initial state: domain initially contains hydrostatic brine
# SPE11a datum pressure is 1.1 bar (input.toml `pressure`), with the datum at the
# top of the rig; pressure increases hydrostatically with depth below it.
depth = domain[:cell_centroids][3, :]
p0 = 1.1 * bar .+ depth .* Jutul.gravity_constant .* 998.39   # 1.1 bar datum + hydrostatic
state0 = setup_reservoir_state(model, Pressure=p0, OverallMoleFractions=[1.0, 0.0])

# ## Time schedule (full SPE11a: 120 h)
# SPE11a injects for 5 h, then monitors up to a total of 120 h. Well 1 is active
# for the whole injection period while Well 2 only injects during its second half
# (2.5–5 h); both are shut for the post-injection monitoring phase. We use three
# force periods with report steps aligned at the 2.5 h and 5 h boundaries:
# 10-minute steps while injecting, 1-hour steps during monitoring.
dt_well1 = fill(10.0 * 60.0, 15)   # 0.0–2.5 h: Well 1 only
dt_both = fill(10.0 * 60.0, 15)    # 2.5–5.0 h: Well 1 + Well 2
dt_post = fill(1.0 * hour, 115)    # 5.0–120.0 h: post-injection monitoring
dt = vcat(dt_well1, dt_both, dt_post)
nstep = length(dt)

# ## Dirichlet (pressure) boundary condition on the top of the domain
# The top layer (k = 1) is the open free-flow boundary; the other three sides
# remain no-flow. The boundary transmissibility is computed automatically from the
# cell permeability and size with `dir = :z`.
top_cells = [c for c in 1:number_of_cells(mesh) if cell_ijk(mesh, c)[3] == 1]
p_bc = 1.115 * bar   # SPE11a free-flow BC (deck BCPROP: DIRICHLET WATER, 1.115 bar)
bc = flow_boundary_condition(top_cells, domain, p_bc; dir=:z, fractional_flow=[1.0, 0.0])

# ## Injection wells (SPE11a specification)
# Each single-perforation well injects pure CO2 at the SPE11a mass rate from
# `input.toml` (1.7e-7 kg/s each). A mass-rate target preserves the kg/s value
# directly. Well 1 injects for the whole 5 h; Well 2 only during the second half.
mass_rate = 1.7e-7 * kg
injector_control = InjectorControl(
    TotalMassRateTarget(mass_rate),
    [0.0, 1.0],
    density=2.0085 * kg / meter^3,
)
shut = DisabledControl()

forces_well1 = setup_reservoir_forces(model, bc=bc,
    control=Dict(:Injector1 => injector_control, :Injector2 => shut))
forces_both = setup_reservoir_forces(model, bc=bc,
    control=Dict(:Injector1 => injector_control, :Injector2 => injector_control))
forces_post = setup_reservoir_forces(model, bc=bc,
    control=Dict(:Injector1 => shut, :Injector2 => shut))

# One forces entry per report step, matching the three periods of the schedule.
forces = vcat(
    fill(forces_well1, length(dt_well1)),
    fill(forces_both, length(dt_both)),
    fill(forces_post, length(dt_post)),
)

parameters = setup_parameters(model)

# ## Run simulation
# Start conservatively because each injector acts on a single small grid cell.
# Use HYPRE BoomerAMG for the CPR pressure stage instead of native smoothed
# aggregation, avoiding its coarse-grid SVD path.
# Each report-step state is stored as JLD2. On later runs, restart=true reloads
# a completed simulation or resumes from the latest state on disk.
output_path = joinpath(@__DIR__, "example3")
ws, states = simulate_reservoir(state0, model, dt,
    forces=forces,
    parameters=parameters,
    output_path=output_path,
    restart=true,
    info_level=1,
    initial_dt=1.0,
    target_its=5,
    timestep_max_increase=1.1,
    timestep_max_decrease=0.25,
    relaxation=Jutul.SimpleRelaxation(
        tol=0.01,
        w_min=0.4,
        dw=0.1,
    ),
    presolve_wells=true,
    max_nonlinear_iterations=15,
    max_timestep_cuts=20,
    linear_solver=:gmres,
    precond=:cprw,
    linear_solver_arg=Dict(
        :amg_type => :hypre,
        :update_interval => :ministep,
        :partial_update => true,
        :update_interval_partial => :iteration,
        :nonlinear_relative_tolerance => 0.05,
        :relaxed_relative_tolerance => 0.1,
        :amg_arg => (
            StrongThreshold=0.25,
            # SmoothType=5,
            # SmoothNumLevels=2,
            # SmoothNumSweeps=1,
            # ILUType=0,
            # ILULevel=0,
            # ILUMaxIter=1,
        ),
        :max_iterations => 100,
    ))

# ## SPE11a sparse-data reporting
# Reconstruct the SPE11a "sparse data" time series so the results can be compared
# against the benchmark. The pyopmspe11 deck encodes the reporting regions in
# FIPNUM.INC: box A = {2, 4, 5, 8}, box B = {3, 6}, box-A seal = {5, 8},
# box-B seal = {6}, remaining seal = {7, 9}, with the pressure observation points
# POP1 = 8 and POP2 = 9. Boxes A/B carry the mobile / immobile (residually
# trapped) / dissolved CO2 inventories; the seal groups carry all CO2 within the
# low-permeability facies. `co2_inventory` does the per-cell mass partitioning
# (mobile vs residual via the critical gas saturation, plus dissolved CO2).
fipnum_full = parse_eclipse_rle_int(joinpath(deck_dir, "FIPNUM.INC"))
fipnum = fipnum_full[active]   # one value per active (submesh) cell

cells_with(codes) = findall(in(codes), fipnum)
boxA_cells = cells_with((2, 4, 5, 8))
boxB_cells = cells_with((3, 6))
boxA_seal_cells = cells_with((5, 8))
boxB_seal_cells = cells_with((6,))
seal_cells = cells_with((5, 6, 7, 8, 9))
pop1_cell = only(cells_with((8,)))
pop2_cell = only(cells_with((9,)))

t_min = cumsum(dt) ./ 60.0

# Per-cell CO2 mass partitioning, replicating JutulDarcy's `co2_inventory` logic
# (we can't call it directly here because the custom `RelativePermeabilities`
# variable set above is not a `ReservoirRelativePermeabilities`). For each cell:
# the gas saturation is split into a residual part `min(Sg, Sgcr)` (immobile) and
# a mobile part `Sg - Sgcr`; dissolved CO2 is the CO2 mass in the liquid phase.
nc = number_of_cells(domain)
pv = poro .* domain[:volumes]                       # pore volume per active cell
sgcr_facies = [kr.critical for kr in krg_tables]    # critical gas sat per facies
sgcr_cell = [sgcr_facies[f] for f in active_facies]
co2_idx = 2   # component order in the co2brine system is (H2O, CO2)

function co2_series(cells)
    mob = zeros(nstep)
    res = zeros(nstep)
    diss = zeros(nstep)
    for s in 1:nstep
        st = states[s]
        S = st[:Saturations]
        rho = st[:PhaseMassDensities]
        X = st[:LiquidMassFractions]
        Y = st[:VaporMassFractions]
        for c in cells
            sg, sl = S[2, c], S[1, c]
            sg_r = min(sg, sgcr_cell[c])
            co2_vap = rho[2, c] * Y[co2_idx, c] * pv[c]
            res[s] += sg_r * co2_vap
            mob[s] += (sg - sg_r) * co2_vap
            diss[s] += rho[1, c] * X[co2_idx, c] * sl * pv[c]
        end
    end
    return (mobile=mob, residual=res, dissolved=diss, total=mob .+ res .+ diss)
end

# Cumulative injected CO2 mass from the well results (mass-balance reference).
co2_rate = zeros(nstep)
for (_, wres) in pairs(ws.wells)
    co2_rate .+= abs.(wres[:CO2_mass_rate])
end
injected = cumsum(co2_rate .* dt)

inv_dom = co2_series(1:nc)
inv_A = co2_series(boxA_cells)
inv_B = co2_series(boxB_cells)
inv_sealA = co2_series(boxA_seal_cells)
inv_sealB = co2_series(boxB_seal_cells)
inv_sealT = co2_series(seal_cells)

# Pressure response relative to the initial (t=0) hydrostatic state `p0`. The
# absolute pressures look flat because the open top pins them near hydrostatic;
# the perturbation from injection is tiny, so we plot Δp to reveal it.
dp1 = [states[s][:Pressure][pop1_cell] - p0[pop1_cell] for s in 1:nstep]
dp2 = [states[s][:Pressure][pop2_cell] - p0[pop2_cell] for s in 1:nstep]

# Boundary efflux diagnostic: the only sink is the open top, so the missing CO2
# (injected − in-domain) must have left through it. We also track the CO2 that
# has reached the top boundary row of cells, and the peak gas saturation there.
loss = injected .- inv_dom.total
inv_top = co2_series(top_cells)
sg_top_max = [maximum(states[s][:Saturations][2, c] for c in top_cells) for s in 1:nstep]

fig_sparse = Figure(size=(1100, 1300))

ax_p = Axis(fig_sparse[1, 1], xlabel="time [min]", ylabel="Δpressure from t=0 [Pa]",
    title="Observation-point pressure response")
lines!(ax_p, t_min, dp1, label="POP1")
lines!(ax_p, t_min, dp2, label="POP2")
axislegend(ax_p)

ax_dom = Axis(fig_sparse[1, 2], xlabel="time [min]", ylabel="CO2 mass [kg]",
    title="Whole-domain CO2 inventory")
lines!(ax_dom, t_min, inv_dom.mobile, label="mobile")
lines!(ax_dom, t_min, inv_dom.residual, label="immobile")
lines!(ax_dom, t_min, inv_dom.dissolved, label="dissolved")
axislegend(ax_dom, position=:lt)

ax_a = Axis(fig_sparse[2, 1], xlabel="time [min]", ylabel="CO2 mass [kg]",
    title="Box A CO2 inventory")
lines!(ax_a, t_min, inv_A.mobile, label="mobA")
lines!(ax_a, t_min, inv_A.residual, label="immA")
lines!(ax_a, t_min, inv_A.dissolved, label="dissA")
axislegend(ax_a, position=:lt)

ax_b = Axis(fig_sparse[2, 2], xlabel="time [min]", ylabel="CO2 mass [kg]",
    title="Box B CO2 inventory")
lines!(ax_b, t_min, inv_B.mobile, label="mobB")
lines!(ax_b, t_min, inv_B.residual, label="immB")
lines!(ax_b, t_min, inv_B.dissolved, label="dissB")
axislegend(ax_b, position=:lt)

ax_seal = Axis(fig_sparse[3, 1], xlabel="time [min]", ylabel="CO2 mass [kg]",
    title="CO2 in seal facies")
lines!(ax_seal, t_min, inv_sealA.total, label="sealA")
lines!(ax_seal, t_min, inv_sealB.total, label="sealB")
lines!(ax_seal, t_min, inv_sealT.total, label="sealTot")
axislegend(ax_seal, position=:lt)

# Authoritative in-domain CO2 mass straight from the solver's TotalMasses, to
# check my phase-reconstructed `inv_dom.total` (which uses a static pore volume).
# If this overlaps `injected`, there is no real loss and my reconstruction
# undercounts; if it overlaps `inv_dom.total`, CO2 genuinely left the domain.
co2_tm = [sum(states[s][:TotalMasses][co2_idx, :]) for s in 1:nstep]

ax_mb = Axis(fig_sparse[3, 2], xlabel="time [min]", ylabel="CO2 mass [kg]",
    title="Mass balance")
lines!(ax_mb, t_min, injected, label="injected")
lines!(ax_mb, t_min, co2_tm, label="in domain (TotalMasses)")
# lines!(ax_mb, t_min, inv_dom.total, label="in domain (reconstructed)")
axislegend(ax_mb, position=:lt)

# Diagnostic #1: confirm the missing mass left through the open top boundary, and
# that it coincides with CO2 reaching the top row of cells.
ax_loss = Axis(fig_sparse[4, 1], xlabel="time [min]", ylabel="CO2 mass [kg]",
    title="Top-boundary CO2 efflux")
lines!(ax_loss, t_min, loss, label="injected − in domain")
lines!(ax_loss, t_min, inv_top.total, label="CO2 in top row")
axislegend(ax_loss, position=:lt)

# The top row holds only a *trace* dissolved CO2 (continuously flushed out by the
# displaced brine), invisible on a linear kg axis — so we show it on a log scale.
# Peak gas saturation there is exactly 0 (`sg_top_max`), i.e. no free gas reaches
# the top seal: the efflux is dissolved CO2 carried out by brine, not free gas.
ax_sgt = Axis(fig_sparse[4, 2], xlabel="time [min]", ylabel="CO2 mass [kg]",
    yscale=log10, title="CO2 in top row (log scale)")
lines!(ax_sgt, t_min, max.(inv_top.total, 1e-30))

fig_sparse

# ## Plot vapor saturation at three time points
fig = Figure(size=(1000, 900))
steps_to_plot = [nstep ÷ 4, nstep ÷ 2, nstep]
plt = nothing
for (row, step) in enumerate(steps_to_plot)
    time_hr = round(sum(dt[1:step]) / hour, digits=2)
    ax = Axis3(fig[row, 1], title="Vapor saturation, hour $time_hr")
    global plt = plot_cell_data!(ax, mesh, states[step][:Saturations][2, :],
        colorrange=(0.0, 1.0), colormap=:viridis)
    ax.azimuth[] = 1.5π
    ax.elevation[] = 0.0
end
Colorbar(fig[:, 2], plt, label="Vapor saturation [-]")
fig

# ## Interactive movie of all time steps
# As in the `co2_sloped.jl` example, `plot_reservoir` opens an interactive
# viewer with a time slider (and a play button) that animates the result
# through every report step. Pick `:Saturations` to follow the vapor plume.
plot_reservoir(model, states, key=:Saturations, step=nstep)


# ## Plot permeability (log10, mD) to show the retained heterogeneity
perm_log = log10.(max.(perm ./ mD, 1e-3))
fig_k, ax_k, plt_k = plot_cell_data(mesh, perm_log, colormap=:viridis)
ax_k.azimuth[] = 1.5π
ax_k.elevation[] = 0.0
ax_k.title = "log10 permeability [mD]"
Colorbar(fig_k[1, 2], plt_k)
fig_k
