# # 2D Two-Phase Flow on the SPE11a Geometry
# <tags: CO2, Compositional, Introduction>
# A simple two-phase miscible CO2-brine flow example that reuses the geometry,
# permeability and porosity of the SPE11a benchmark (a 2.8 m × 1.2 m vertical
# cross-section with 7 facies). The domain is initially fully saturated with a
# heavy liquid phase. A lighter vapor phase is injected from two point source
# terms — placed at the SPE11a injection cells — and rises towards the top
# under gravity.
#
# Three of the four boundaries are closed (no-flow, the JutulDarcy default).
# The top boundary is an open Dirichlet pressure boundary that lets the
# displaced fluids escape.
#
# The SPE11a deck (generated by pyopmspe11) contains a sealing facies with zero
# permeability. We keep these cells active in the mesh and assign them a small
# but nonzero permeability and porosity, so they act as a tight, numerically
# well-posed seal. (Leaving the permeability at exactly zero would create
# isolated, non-flowing cells that hurt convergence.)
#
# Generate the deck before running this script:
#   cd examples/workflow/spe11a_data && uv run pyopmspe11 -i input.toml -m deck -o output

println("Loading packages and defining units/paths...")
using Jutul, JutulDarcy, GeoEnergyIO
using HYPRE
using GLMakie
using Printf: @sprintf
using SpecialFunctions: erf

Darcy, bar, kg, meter, day = si_units(:darcy, :bar, :kilogram, :meter, :day)
mD = 1e-3 * Darcy
hour = 3600.0   # seconds

scientific_tick_labels(values) = [@sprintf("%.1e", v) for v in values]

deck_dir = joinpath(@__DIR__, "spe11a_data", "output", "deck")
deck_path = joinpath(deck_dir, "OUTPUT.DATA")

# ## Parse the facies map from FLUXNUM.INC
# GeoEnergyIO does not support FLUXNUM or EQUALREG, so we parse the run-length
# encoded integer file directly to get one facies index per cell.
println("Parsing facies map from FLUXNUM.INC...")
function parse_eclipse_rle_int(filepath)
    values = Int[]
    open(filepath) do f
        for line in eachline(f)
            line = split(strip(line), "--")[1]
            for token in split(line)
                token == "/" && return values
                if contains(token, "*")
                    n, v = split(token, "*")
                    append!(values, fill(parse(Int, v), parse(Int, n)))
                elseif all(c -> isdigit(c) || c == '-', token)
                    push!(values, parse(Int, token))
                end
            end
        end
    end
    return values
end

facies = parse_eclipse_rle_int(joinpath(deck_dir, "FLUXNUM.INC"))

# Permeability [mD] and porosity per facies (facies 7 is the sealing rock). The
# SPE11a deck defines the seal with K = 0 and phi = 0; we instead give it a small
# nonzero permeability/porosity so the seal cells can be kept active (see below)
# without becoming isolated, non-flowing degrees of freedom.
seal_perm_mD = 1e-3   # tight seal permeability [mD] (deck value is 0.0)
seal_poro = 1e-3      # small seal porosity [-]      (deck value is 0.0)
perm_mD = [44529.9988, 506624.985, 1013249.97, 2026499.95, 4052999.88, 10132499.7, seal_perm_mD]
phi_tab = [0.44, 0.43, 0.44, 0.45, 0.43, 0.46, seal_poro]

# ## Parse the SPE11a saturation-function tables
# The generated deck writes the benchmark constitutive laws in SGWFN as
# [Sg, krg, krw, pc] with pc in METRIC deck pressure units (bar).
println("Parsing SPE11a saturation-function tables...")
function parse_sgwfn_tables(filepath)
    tables = Matrix{Float64}[]
    rows = Vector{Float64}[]
    in_sgwfn = false
    open(filepath) do f
        for line in eachline(f)
            line = strip(split(line, "--")[1])
            isempty(line) && continue
            for token in split(line)
                if token == "SGWFN"
                    in_sgwfn = true
                    continue
                end
                in_sgwfn || continue
                if token == "/"
                    if !isempty(rows)
                        push!(tables, reduce(vcat, transpose.(rows)))
                        empty!(rows)
                    end
                    continue
                end
                push!(rows, [parse(Float64, token)])
                if length(rows) >= 4 && all(length(r) == 1 for r in rows[(end-3):end])
                    vals = vcat(rows[(end-3):end]...)
                    resize!(rows, length(rows) - 4)
                    push!(rows, vals)
                end
            end
        end
    end
    return tables
end

sgwfn_tables = parse_sgwfn_tables(joinpath(deck_dir, "TABLES.INC"))

# ## Register OPM-specific keywords for the parser to skip
# We only need the grid geometry from the deck, so we skip the keywords that
# GeoEnergyIO does not understand and inject our own per-cell properties below.
println("Registering deck keywords to skip during parsing...")
let skip = GeoEnergyIO.InputParser.skip_kw!
    skip(:DISGASW, 0)
    skip(:VAPWAT, 0)
    skip(:EQUALREG, Inf)
    skip(:BCCON, Inf)
    skip(:SGWFN, Inf)
    skip(:DIFFAWAT, 1)
    skip(:DIFFAGAS, 1)
    skip(:THCO2MIX, 1)
    skip(:BCPROP, Inf)
end

# ## Parse the deck and inject facies-based properties
println("Parsing deck and injecting facies-based porosity/permeability...")
data = parse_data_file(deck_path)
n_cells = length(facies)
poro_full = [phi_tab[facies[c]] for c in 1:n_cells]
permx_full = [perm_mD[facies[c]] * mD for c in 1:n_cells]

data["GRID"]["PORO"] = poro_full
data["GRID"]["PERMX"] = permx_full
data["GRID"]["PERMY"] = permx_full
data["GRID"]["PERMZ"] = permx_full   # isotropic

# Build the full domain just to recover the SPE11a mesh geometry.
full_domain = reservoir_domain(data)
full_mesh = physical_representation(full_domain)

# ## Keep all cells active (including the seal)
# Previously the impermeable facies-7 cells were dropped from the mesh. We now
# keep every cell active: the seal carries a small nonzero permeability/porosity
# (see above), so it remains a well-posed barrier rather than a set of isolated,
# non-flowing cells. Setting `active = 1:n_cells` makes the downstream submesh
# indexing (`active[...]`, `searchsortedfirst(active, ...)`) a no-op.
println("Keeping all cells active and building the reservoir domain...")
active = collect(1:n_cells)
mesh = full_mesh

poro = poro_full[active]
perm = permx_full[active]
# Molecular diffusion per phase (SPE11a `diffusion` in input.toml): liquid 1e-9,
# gas 1.6e-5 [m^2/s]. The co2brine phases are ordered (LiquidPhase, VaporPhase),
# so row 1 = liquid, row 2 = gas. It must be given as an (nphase x ncell) matrix
# (one value per cell, per phase). Internally this becomes per-phase face
# diffusivities (D_alpha * porosity), adding Fickian component fluxes from
# gradients of the dissolved-CO2 / vaporized-H2O mass fractions.
diffusion = repeat([1e-9, 1.6e-5], 1, length(active))
domain = reservoir_domain(mesh, permeability=perm, porosity=poro, diffusion=diffusion)

# ## Locate the SPE11a injection cells
# SPE11a defines two injection locations. The pyopmspe11 deck places them at
# full-grid cells (i,j,k) = (91,1,101) (lower) and
# (180,1,43) (upper). We map them onto the active cell ordering via the logical
# (i,j,k) index; with all cells active this mapping is the identity, but it stays
# correct if cells are ever dropped again.
println("Locating SPE11a injection cells and creating wells...")
inj_ijk = [(91, 1, 101), (180, 1, 43)]
nc_full = number_of_cells(full_mesh)
inj_full = [findfirst(c -> cell_ijk(full_mesh, c) == ijk, 1:nc_full) for ijk in inj_ijk]
inj_cells = [searchsortedfirst(active, c) for c in inj_full]
well_radius = 9e-4   # SPE11a well bore radius [m] (input.toml `radius`)
injectors = [
    setup_well(domain, inj_cells[1], name=:Injector1, simple_well=true, radius=well_radius),
    setup_well(domain, inj_cells[2], name=:Injector2, simple_well=true, radius=well_radius),
]

# ## Miscible CO2-brine model with SPE11a constitutive laws
# The :co2brine model uses the CSP11/SPE11 H2O-CO2 property tables and K-values,
# so dissolved CO2 in brine and vaporized water in CO2 are represented.
println("Setting up the miscible CO2-brine model and constitutive laws...")
domain[:temperature] = fill(20.0 + 273.15, number_of_cells(domain))
model = setup_reservoir_model(domain, :co2brine,
    wells=injectors,
    co2_physics=:kvalue,
    dz_max=0.05,
    dp_max_rel=0.1,
    fast_flash=true)

active_facies = facies[active]
# SPE11a capillary-pressure parameters per facies (input.toml `safu`): irreducible
# water saturation `swi` and entry pressure `pen` [Pa]. The generated deck clamps
# the erf capillary curve at penmax = 2500 Pa, but the benchmark description
# prescribes a maximum capillary pressure of 95000 Pa, so we recompute Pcgw
# analytically here rather than using the clamped deck values.
pc_swi = [0.32, 0.14, 0.12, 0.12, 0.12, 0.10, 0.0]
pc_pen = [1500.0, 300.0, 100.0, 25.0, 10.0, 1.0, 0.0]
penmax = 95000.0   # SPE11a maximum capillary pressure [Pa]
krw_tables = []
krg_tables = []
pcgw_tables = []
for (i, tab) in enumerate(sgwfn_tables)
    sg = tab[:, 1]
    krg = tab[:, 2]
    krw = tab[:, 3]
    swi, pen = pc_swi[i], pc_pen[i]
    pcgw = map(sg) do sg_i
        t = (1.0 - sg_i - swi) / (1.0 - swi)   # normalized effective water saturation
        t > 1e-10 ? penmax * erf(pen * t^(-0.5) * sqrt(π) / (2.0 * penmax)) : penmax
    end

    sw = reverse(1.0 .- sg)
    push!(krw_tables, PhaseRelativePermeability(sw, reverse(krw), label=:w))
    push!(krg_tables, PhaseRelativePermeability(sg, krg, label=:g))
    push!(pcgw_tables, get_1d_interpolator(sg, pcgw, constant_dx=false))
end

replace_variables!(model,
    RelativePermeabilities=RelativePermeabilities(
        (tuple(krw_tables...), tuple(krg_tables...)),
        regions=active_facies
    )
)
set_secondary_variables!(
    reservoir_model(model),
    CapillaryPressure=JutulDarcy.SimpleCapillaryPressure(
        (tuple(pcgw_tables...),),
        regions=active_facies
    )
)

# ## Initial state: domain initially contains hydrostatic brine
# SPE11a datum pressure is 1.1 bar (input.toml `pressure`), with the datum at the
# top of the rig; pressure increases hydrostatically with depth below it.
println("Initializing hydrostatic brine state...")
depth = domain[:cell_centroids][3, :]
p0 = 1.1 * bar .+ depth .* Jutul.gravity_constant .* 998.39   # 1.1 bar datum + hydrostatic
state0 = setup_reservoir_state(model, Pressure=p0, OverallMoleFractions=[1.0, 0.0])

# ## Time schedule (full SPE11a: 120 h)
# SPE11a injects for 5 h, then monitors up to a total of 120 h. Well 1 is active
# for the whole injection period while Well 2 only injects during its second half
# (2.5–5 h); both are shut for the post-injection monitoring phase. We use three
# force periods with report steps aligned at the 2.5 h and 5 h boundaries:
# 10-minute steps while injecting, 1-hour steps during monitoring.
println("Building the 120-hour SPE11a time schedule...")
dt_well1 = fill(10.0 * 60.0, 15)   # 0.0–2.5 h: Well 1 only
dt_both = fill(10.0 * 60.0, 15)    # 2.5–5.0 h: Well 1 + Well 2
dt_post = fill(1.0 * hour, 115)    # 5.0–120.0 h: post-injection monitoring
dt = vcat(dt_well1, dt_both, dt_post)
nstep = length(dt)

# ## Dirichlet (pressure) boundary condition on the top of the domain
# The top layer (k = 1) is the open free-flow boundary; the other three sides
# remain no-flow. The boundary transmissibility is computed automatically from the
# cell permeability and size with `dir = :z`.
println("Applying the open top pressure boundary condition...")
top_cells = [c for c in 1:number_of_cells(mesh) if cell_ijk(mesh, c)[3] == 1]
p_bc = 1.115 * bar   # SPE11a free-flow BC (deck BCPROP: DIRICHLET WATER, 1.115 bar)
bc = flow_boundary_condition(top_cells, domain, p_bc; dir=:z, fractional_flow=[1.0, 0.0])

# ## Injection wells (SPE11a specification)
# Each single-perforation well injects pure CO2 at the SPE11a mass rate from
# `input.toml` (1.7e-7 kg/s each). A mass-rate target preserves the kg/s value
# directly. Well 1 injects for the whole 5 h; Well 2 only during the second half.
println("Configuring injection controls and report-step forces...")
mass_rate = 1.7e-7 * kg
injector_control = InjectorControl(
    TotalMassRateTarget(mass_rate),
    [0.0, 1.0],
    density=2.0085 * kg / meter^3,
)
shut = DisabledControl()

# Work around a JutulDarcy limitation in `check_well_limit` for injectors:
# every well control gets an automatic operating limit derived from its target via
# `as_limit`. For a `TotalMassRateTarget` that limit is `mrat`, which the injector
# limit-check does not handle, so the run errors on the first step. The limit is
# regenerated from the target inside `update_before_step_multimodel!` regardless of
# `set_default_limits`, so it cannot be suppressed through `setup_reservoir_forces`.
# The `mrat` entry is only ever a self-limit equal to the target value and has no
# competing constraint to switch to, so dropping it is behaviour-neutral. We make
# `as_limit` return no limit for a `TotalMassRateTarget` (the proper fix is to add
# `mrat` handling in JutulDarcy's `check_well_limit`).
JutulDarcy.as_limit(::JutulDarcy.TotalMassRateTarget) = (;)

forces_well1 = setup_reservoir_forces(model, bc=bc,
    control=Dict(:Injector1 => injector_control, :Injector2 => shut))
forces_both = setup_reservoir_forces(model, bc=bc,
    control=Dict(:Injector1 => injector_control, :Injector2 => injector_control))
forces_post = setup_reservoir_forces(model, bc=bc,
    control=Dict(:Injector1 => shut, :Injector2 => shut))

# One forces entry per report step, matching the three periods of the schedule.
forces = vcat(
    fill(forces_well1, length(dt_well1)),
    fill(forces_both, length(dt_both)),
    fill(forces_post, length(dt_post)),
)

parameters = setup_parameters(model)

# ## Run simulation
# Start conservatively because each injector acts on a single small grid cell.
# Use HYPRE BoomerAMG for the CPR pressure stage instead of native smoothed
# aggregation, avoiding its coarse-grid SVD path.
# Each report-step state is stored as JLD2. On later runs, restart=true reloads
# a completed simulation or resumes from the latest state on disk.
println("Running the reservoir simulation...")
output_path = joinpath(@__DIR__, "spe11a")
ws, states = simulate_reservoir(state0, model, dt,
    forces=forces,
    parameters=parameters,
    output_path=output_path,
    restart=true,
    info_level=1,
    initial_dt=1.0,
    target_its=5,
    timestep_max_increase=1.1,
    timestep_max_decrease=0.25,
    relaxation=Jutul.SimpleRelaxation(
        tol=0.01,
        w_min=0.4,
        dw=0.1,
    ),
    presolve_wells=true,
    max_nonlinear_iterations=15,
    max_timestep_cuts=20,
    linear_solver=:gmres,
    precond=:cprw,
    linear_solver_arg=Dict(
        :amg_type => :hypre,
        :update_interval => :ministep,
        :partial_update => true,
        :update_interval_partial => :iteration,
        :nonlinear_relative_tolerance => 0.05,
        :relaxed_relative_tolerance => 0.1,
        :amg_arg => (
            StrongThreshold=0.25,
            # SmoothType=5,
            # SmoothNumLevels=2,
            # SmoothNumSweeps=1,
            # ILUType=0,
            # ILULevel=0,
            # ILUMaxIter=1,
        ),
        :max_iterations => 100,
    ))

# ## SPE11a sparse-data reporting
# Reconstruct the SPE11a "sparse data" panels used in the benchmark overview:
# POP1 pressure, CO2 in sealing units, mobile/dissolved CO2 in boxes A/B, and the
# Box C convection metric. The pyopmspe11 deck encodes these regions in FIPNUM.
println("Plotting SPE11a sparse-data benchmark panels...")
fipnum_full = parse_eclipse_rle_int(joinpath(deck_dir, "FIPNUM.INC"))
fipnum = fipnum_full[active]   # one value per active (submesh) cell

cells_with(codes) = findall(in(codes), fipnum)
boxA_cells = cells_with((2, 4, 5, 8))
boxB_cells = cells_with((3, 6))
seal_cells = cells_with((5, 6, 7, 8, 9))
boxC_cells = cells_with((4,))
pop1_cell = only(cells_with((8,)))

t_hr = cumsum(dt) ./ hour

# Per-cell CO2 mass partitioning, replicating JutulDarcy's `co2_inventory` logic
# (we can't call it directly here because the custom `RelativePermeabilities`
# variable set above is not a `ReservoirRelativePermeabilities`). For each cell:
# the gas saturation is split into a residual part `min(Sg, Sgcr)` (immobile) and
# a mobile part `Sg - Sgcr`; dissolved CO2 is the CO2 mass in the liquid phase.
nc = number_of_cells(domain)
pv = poro .* domain[:volumes]                       # pore volume per active cell
sgcr_facies = [kr.critical for kr in krg_tables]    # critical gas sat per facies
sgcr_cell = [sgcr_facies[f] for f in active_facies]
co2_idx = 2   # component order in the co2brine system is (H2O, CO2)

function co2_series(cells)
    mob = zeros(nstep)
    res = zeros(nstep)
    diss = zeros(nstep)
    for s in 1:nstep
        st = states[s]
        S = st[:Saturations]
        rho = st[:PhaseMassDensities]
        X = st[:LiquidMassFractions]
        Y = st[:VaporMassFractions]
        for c in cells
            sg, sl = S[2, c], S[1, c]
            sg_r = min(sg, sgcr_cell[c])
            co2_vap = rho[2, c] * Y[co2_idx, c] * pv[c]
            res[s] += sg_r * co2_vap
            mob[s] += (sg - sg_r) * co2_vap
            diss[s] += rho[1, c] * X[co2_idx, c] * sl * pv[c]
        end
    end
    return (mobile=mob, residual=res, dissolved=diss, total=mob .+ res .+ diss)
end

inv_A = co2_series(boxA_cells)
inv_B = co2_series(boxB_cells)
inv_sealT = co2_series(seal_cells)

# The Box C convection metric follows pyopmspe11's sparse-data definition for
# SPE11a: sum of dissolved-CO2 concentration jumps across x/z faces, weighted by
# the opposite cell dimensions. It has units of length [m].
nx = maximum(cell_ijk(mesh, c)[1] for c in 1:nc)
ny = maximum(cell_ijk(mesh, c)[2] for c in 1:nc)
stride_z = nx * ny
boxC_mask = fipnum .== 4
boxC_x_cells = findall(c -> c > 1 && boxC_mask[c-1], 1:nc)
boxC_z_cells = findall(c -> c + stride_z <= nc && boxC_mask[c+stride_z], 1:nc)
dx = data["GRID"]["DX"][active]
dz = data["GRID"]["DZ"][active]

function boxC_convection(step)
    # Use dissolved CO2 in the liquid phase as the local concentration proxy.
    X = states[step][:LiquidMassFractions][co2_idx, :]
    xcw = X ./ max(maximum(X), eps())
    dxv = abs.(xcw[boxC_x_cells] .- xcw[boxC_cells])
    dzv = abs.(xcw[boxC_z_cells] .- xcw[boxC_cells])
    return sum(dxv .* dz[boxC_cells] .+ dzv .* dx[boxC_cells])
end

p_pop1 = [states[s][:Pressure][pop1_cell] for s in 1:nstep]
m_c = [boxC_convection(s) for s in 1:nstep]

fig_sparse = Figure(size=(1200, 1500))

ax_p = Axis(fig_sparse[1, 1], xscale=log10, ytickformat=scientific_tick_labels,
    ylabel="pressure [Pa]", title="POP 1")
lines!(ax_p, t_hr, p_pop1, label="p1")

ax_seal = Axis(fig_sparse[1, 2], xscale=log10, ytickformat=scientific_tick_labels, yaxisposition=:right,
    ylabel="mass [kg]", title="CO2 in sealing units")
lines!(ax_seal, t_hr, inv_sealT.total, label="sealTot")
ylims!(ax_seal, -2e-5, 7.2e-4)
ax_seal.yticks = 0:1e-4:7e-4

ax_moba = Axis(fig_sparse[2, 1], xscale=log10, ytickformat=scientific_tick_labels, ylabel="mass [kg]",
    title="Box A: mobile gaseous CO2")
lines!(ax_moba, t_hr, inv_A.mobile, label="mobA")
ylims!(ax_moba, -1e-4, 1.1e-3)
ax_moba.yticks = 0:2e-4:1e-3

ax_dissa = Axis(fig_sparse[2, 2], xscale=log10, ytickformat=scientific_tick_labels,
    yaxisposition=:right, ylabel="mass [kg]",
    title="Box A: dissolved CO2")
lines!(ax_dissa, t_hr, inv_A.dissolved, label="dissA")
ylims!(ax_dissa, -1e-4, 2.1e-3)
ax_dissa.yticks = 0:5e-4:2e-3

ax_mobb = Axis(fig_sparse[3, 1], xscale=log10, ytickformat=scientific_tick_labels,
    xlabel="time [h]", ylabel="mass [kg]",
    title="Box B: mobile gaseous CO2")
lines!(ax_mobb, t_hr, inv_B.mobile, label="mobB")
ylims!(ax_mobb, -1e-5, 4.5e-4)
ax_mobb.yticks = 0:1e-4:4e-4

ax_mc = Axis(fig_sparse[3, 2], xscale=log10, ytickformat=scientific_tick_labels,
    yaxisposition=:right, xlabel="time [h]",
    ylabel="M [m]", title="Box C: convection")
lines!(ax_mc, t_hr, m_c, label="M")
ylims!(ax_mc, -1, 16)
ax_mc.yticks = 0:2.5:15

for ax in (ax_p, ax_seal, ax_moba, ax_dissa, ax_mobb, ax_mc)
    xlims!(ax, 0.1, maximum(t_hr))
    ax.xminorticksvisible = true
    ax.xminorticks = IntervalsBetween(9)
end

fig_sparse

# %%
# Plot domain CO2 partitioning by phase and mobility
println("Plotting dissolved, mobile vapor, and immobile vapor CO2...")
inv_domain = co2_series(1:nc)

fig_co2_partition = Figure(size=(900, 500))
ax_co2_partition = Axis(fig_co2_partition[1, 1],
    xscale=log10,
    ytickformat=scientific_tick_labels,
    xlabel="time [h]",
    ylabel="CO2 mass [kg]",
    title="CO2 partitioning in the domain"
)
lines!(ax_co2_partition, t_hr, inv_domain.dissolved, label="liquid phase (dissolved)")
lines!(ax_co2_partition, t_hr, inv_domain.mobile, label="vapor phase (mobile)")
lines!(ax_co2_partition, t_hr, inv_domain.residual, label="vapor phase (immobile)")
xlims!(ax_co2_partition, 0.1, maximum(t_hr))
axislegend(ax_co2_partition, position=:lt)
fig_co2_partition

# %%
# Plot result in interactive viewer
# If you have interactive plotting available, you can explore all timesteps
# in the model output interactively.
plot_reservoir(model, states)

# %%
# Plot total injected CO2 mass and total CO2 component mass in the domain
println("Plot total injected CO2 mass...")
injected_rate = [
    s <= length(dt_well1) ? mass_rate :
    s <= length(dt_well1) + length(dt_both) ? 2.0 * mass_rate :
    0.0
    for s in 1:nstep
]
injected_mass = cumsum(injected_rate .* dt)

total_co2_mass = [
    sum(states[s][:TotalMasses][2, :])
    for s in 1:nstep
]

fig_mass = Figure(resolution=(900, 500))
ax_mass = Axis(fig_mass[1, 1],
    xscale=log10,
    ytickformat=scientific_tick_labels,
    xlabel="time [h]",
    ylabel="mass [kg]",
    title="Injected CO2 mass and total CO2 mass in domain"
)
lines!(ax_mass, t_hr, injected_mass, label="injected CO2 mass")
lines!(ax_mass, t_hr, total_co2_mass, label="domain CO2 mass")
axislegend(ax_mass, position=:rb)
fig_mass
